### ISSUE TITLE
update-display process hangs occasionally and sigtimedwait timeout is not handled

### ISSUE THREAD

**Issue by szantaii** [szantaii/slow-movie-frame-10.3#4]
Unfortunately the `update-display` process hanged once again, now in the `EPD_IT8951_Clear_Refresh` function call. (See the `gdb` outputs of `slow-movie-player` and `update-display` below this paragraph.) Moreover, since I forgot to handle timeout of `sigtimedwait` in [`Display::update`](https://github.com/szantaii/slow-movie-frame-10.3/blob/06d4dfabb508fb90bcb944f9f2d26280a9fdd61b/src/slow-movie-player-service/display.py#L99), the service did not stop, therefore the same image was displayed on my e-paper device for about a week and unfortunately that caused burn-ins on it.

```console
$ sudo gdb -ex 'set pagination off' -ex 'attach 105040' -ex 'thread apply all bt full' -ex 'detach' -ex 'q'
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 105040
[New LWP 105053]
[New LWP 105054]
[New LWP 105055]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
0x0000007fb4e74e80 in __GI___sigtimedwait (set=0x7fdbed8760, info=0x7fdbed87e0, timeout=0x7fdbed86d0) at ../sysdeps/unix/sysv/linux/sigtimedwait.c:29
29	../sysdeps/unix/sysv/linux/sigtimedwait.c: No such file or directory.

Thread 4 (Thread 0x7f9eea11c0 (LWP 105055) "python3"):
#0  syscall () at ../sysdeps/unix/sysv/linux/aarch64/syscall.S:38
No locals.
#1  0x0000007fad6979a0 in ?? () from /lib/aarch64-linux-gnu/libtbb.so.2
No symbol table info available.
#2  0x0000007fad6979d0 in ?? () from /lib/aarch64-linux-gnu/libtbb.so.2
No symbol table info available.
#3  0x0000007fb50f3648 in start_thread (arg=0x7f9eea0ac0) at pthread_create.c:477
        ret = <optimized out>
        pd = 0x7f9eea0ac0
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {548126987740, 548143769816, 548143769614, 548143769776, 548143769615, 548126984896, 0, 548498685952, 548143773888, 548126986688, 548126984608, 10104630060549434241, 0, 10104630060153395057, 4629159525935480832, 4606957238818648883, 4652464705678344192, 4607297895713539729, 4607297895713539729, 0, 0, 0}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#4  0x0000007fb4f12c1c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78
No locals.

Thread 3 (Thread 0x7f9f6a21c0 (LWP 105054) "python3"):
#0  syscall () at ../sysdeps/unix/sysv/linux/aarch64/syscall.S:38
No locals.
#1  0x0000007fad6979a0 in ?? () from /lib/aarch64-linux-gnu/libtbb.so.2
No symbol table info available.
#2  0x0000007fad6979d0 in ?? () from /lib/aarch64-linux-gnu/libtbb.so.2
No symbol table info available.
#3  0x0000007fb50f3648 in start_thread (arg=0x7f9f6a1ac0) at pthread_create.c:477
        ret = <optimized out>
        pd = 0x7f9f6a1ac0
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {548135380444, 549150613832, 549150613630, 549150613792, 549150613631, 548135377600, 0, 548498685952, 548495681344, 548135379392, 548135377312, 10104630060549434241, 0, 10104630060178556785, 4629159525935480832, 4606957238818648883, 4652464705678344192, 4607297895713539729, 4607297895713539729, 0, 0, 0}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#4  0x0000007fb4f12c1c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78
No locals.

Thread 2 (Thread 0x7f9fea31c0 (LWP 105053) "python3"):
#0  syscall () at ../sysdeps/unix/sysv/linux/aarch64/syscall.S:38
No locals.
#1  0x0000007fad6979a0 in ?? () from /lib/aarch64-linux-gnu/libtbb.so.2
No symbol table info available.
#2  0x0000007fad6979d0 in ?? () from /lib/aarch64-linux-gnu/libtbb.so.2
No symbol table info available.
#3  0x0000007fb50f3648 in start_thread (arg=0x7f9fea2ac0) at pthread_create.c:477
        ret = <optimized out>
        pd = 0x7f9fea2ac0
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {548143773148, 549150613832, 549150613630, 549150613792, 549150613631, 548143770304, 0, 548498685952, 548495681344, 548143772096, 548143770016, 10104630060549434241, 0, 10104630060170180465, 4629159525935480832, 4606957238818648883, 4652464705678344192, 4607297895713539729, 4607297895713539729, 0, 0, 0}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#4  0x0000007fb4f12c1c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78
No locals.

Thread 1 (Thread 0x7fb4e3e040 (LWP 105040) "python3"):
#0  0x0000007fb4e74e80 in __GI___sigtimedwait (set=0x7fdbed8760, info=0x7fdbed87e0, timeout=0x7fdbed86d0) at ../sysdeps/unix/sysv/linux/sigtimedwait.c:29
        _sys_result = 18446744073709551612
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
        result = <optimized out>
#1  0x00000000004318d4 in ?? ()
No symbol table info available.
#2  0x00000000004b279c in ?? ()
No symbol table info available.
#3  0x000000000049c258 in _PyEval_EvalFrameDefault ()
No symbol table info available.
#4  0x00000000004b1a48 in _PyFunction_Vectorcall ()
No symbol table info available.
#5  0x0000000000498218 in _PyEval_EvalFrameDefault ()
No symbol table info available.
#6  0x00000000004b1a48 in _PyFunction_Vectorcall ()
No symbol table info available.
#7  0x0000000000498218 in _PyEval_EvalFrameDefault ()
No symbol table info available.
#8  0x00000000004964f8 in ?? ()
No symbol table info available.
#9  0x0000000000496290 in _PyEval_EvalCodeWithName ()
No symbol table info available.
#10 0x00000000005976fc in PyEval_EvalCode ()
No symbol table info available.
#11 0x00000000005c850c in ?? ()
No symbol table info available.
#12 0x00000000005c2520 in ?? ()
No symbol table info available.
#13 0x00000000005c8458 in ?? ()
No symbol table info available.
#14 0x00000000005c7c38 in PyRun_SimpleFileExFlags ()
No symbol table info available.
#15 0x00000000005b7afc in Py_RunMain ()
No symbol table info available.
#16 0x0000000000587638 in Py_BytesMain ()
No symbol table info available.
#17 0x0000007fb4e60e18 in __libc_start_main (main=0x587538 <_start+56>, argc=2, argv=0x7fdbed9368, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=<optimized out>) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {6916816, 0, 5797120, 0, 0, 0, 0, 0, 0, 0, 549150626320, 10104630060521706253, 0, 10104630059163372737, 0, 0, 0, 0, 0, 0, 0, 0}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x8d5100 <__libc_start_main@got.plt>, 0x587534 <_start+52>}, data = {prev = 0x0, cleanup = 0x0, canceltype = 9261312}}}
        not_first_call = <optimized out>
#18 0x0000000000587534 in _start ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
Detaching from program: /usr/bin/python3.9, process 105040
[Inferior 1 (process 105040) detached]
```

```console
$ sudo gdb -ex 'set pagination off' -ex 'attach 105060' -ex 'thread apply all bt full' -ex 'detach' -ex 'q'
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 105060
Reading symbols from /opt/slow-movie-player/update-display...
Reading symbols from /lib/aarch64-linux-gnu/libm.so.6...
Reading symbols from /usr/lib/debug/.build-id/8d/efd8eb01d73f30848d9656f10df58465ab9a2e.debug...
Reading symbols from /lib/aarch64-linux-gnu/libpthread.so.0...
Reading symbols from /usr/lib/debug/.build-id/e5/a4fbb31ac8f9324067dd30930fee0eb32a490f.debug...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
Reading symbols from /lib/aarch64-linux-gnu/libc.so.6...
Reading symbols from /usr/lib/debug/.build-id/bc/b0be0a4d5929b9244446b6e495b05fd335a306.debug...
Reading symbols from /lib/ld-linux-aarch64.so.1...
Reading symbols from /usr/lib/debug/.build-id/0c/157faa0bf57d35e8fa64ccb41135d5ee593b4e.debug...
0x000000557d94935c in bcm2835_peri_read (paddr=0x7fb8f17034) at bcm2835.c:212
212	       ret = *paddr;

Thread 1 (Thread 0x7fb9d17040 (LWP 105060) "update-display"):
#0  0x000000557d94935c in bcm2835_peri_read (paddr=0x7fb8f17034) at bcm2835.c:212
        ret = 268599807
#1  0x000000557d94971c in bcm2835_gpio_lev (pin=24 '\030') at bcm2835.c:345
        paddr = 0x7fb8f17034
        shift = 24 '\030'
        value = 268599807
#2  0x000000557d9439b8 in EPD_IT8951_Clear_Refresh ()
No symbol table info available.
#3  0x000000557d941c04 in display_4bpp_image ()
No symbol table info available.
#4  0x000000557d94150c in main ()
No symbol table info available.
Detaching from program: /opt/slow-movie-player/update-display, process 105060
[Inferior 1 (process 105060) detached]
```

I have tried to do full refresh-es to mitigate the effects of the display burn-in but it did not help. I have disassembled and assembled the picture frame and I may have damaged the device since it displays images with some artifacts now.

Until I get a new display, I will do the following:

1. Make sure that the service is always restarted, whatever happens.
2. Set a timeout for the `slow-movie-player.service` start in case of the initial screen clearing hangs.
3. Decrease the default `refresh_timeout` from 300 seconds to 180 seconds as recommended on the [Waveshare wiki](https://www.waveshare.com/wiki/10.3inch_e-Paper_HAT_(D)#accordion5).
4. Add zoom functionality image processing to avoid using black bars as padding.
5. Handle `sigtimedwait` timeouts in [`Display::update`](https://github.com/szantaii/slow-movie-frame-10.3/blob/06d4dfabb508fb90bcb944f9f2d26280a9fdd61b/src/slow-movie-player-service/display.py#L99).

**Comment by szantaii** [comment]
I have implemented the aforementioned changes on the [further-improvements](https://github.com/szantaii/slow-movie-frame-10.3/tree/further-improvements) branch and I will be running the display for a couple of weeks with those changes.

On top of that, I will do some experiments with putting the e-paper device into sleep between refresh operations as mentioned on the [Waveshare wiki](https://www.waveshare.com/wiki/10.3inch_e-Paper_HAT_(D)#accordion5):

> During the standby process (that is, after the refresh operation), it is recommended that the customer set the e-ink screen to sleep mode, or power off (the power supply part of the ink screen can be disconnected with an analog switch) to reduce power consumption and prolong the life of the e-ink screen. (If some e-ink screens are powered on for a long time, the screen will be damaged beyond repair.)

However, it mentions standby (poweroff) process and I am not sure that if I have to call another init after putting the display into sleep mode. So, there are a couple of things I have to look into regarding this change.
